title: SimSearch
description: An IGB plugin to identify and compare occurrences of (epi)genomics feature patterns in multiple genome browser tracks.
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]

plugins:
  - jekyll-feed